export const APP_CONSTS = {
  TRANSLATIONS_KEY_PREFIX: './assets/i18n/',
  SUPPORTED_LANGUAGES: ['en', 'pl'],
  GLOBALISATION: {
    FRACTION_DIGITS_IGNORE: 3
  },
  LOCAL_STORAGE_KEYS: {
    TURN_GEOLOCATION: 'SETTINGS__TURN_GEOLOCATION',
    LANGUAGE: 'SETTINGS__LANGUAGE_KEY'
  }
};
