{{- if .Values.tls.enabled -}}
{{- $fullName := include "air-tracker-app.fullname" . -}}
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: {{ $fullName }}
spec:
  acme:
    # The ACME server URL
    {{- if .Values.tls.isProd }}
    server: https://acme-v02.api.letsencrypt.org/directory
    {{- else }}
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    {{- end }}
    # Email address used for ACME registration
    email: {{ .Values.tls.email }}
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: {{ $fullName }}-private-key
      # Enable the HTTP-01 challenge provider
    solvers:
      - http01:
          ingress:
            class:  nginx
{{- end }}
