apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "air-tracker-app.fullname" . }}
  labels:
    {{- include "air-tracker-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "air-tracker-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "air-tracker-app.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          env:
              {{- $root := . }}
              {{- range $ref, $values := .Values.secrets }}
              {{- range $key, $value := $values }}
              - name: {{ $ref }}__{{ $key }}
                valueFrom:
                  secretKeyRef:
                    name: {{ template "air-tracker-app.fullname" $root }}-{{ $ref | lower }}
                    key: {{ $key }}
              {{- end }}
              {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
