name: Publish Helm Release

on:
  push:
    branches: [ master ]
    paths:
      - "charts/**"
  pull_request:
    branches: [ master ]
  release:
    types: [published, created, edited]
env:
  REF_VAR: github.ref  #refs/heads/<branch_name> || refs/tags/<tag_name>.

jobs:
  build-helm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set version of packages
      run: echo $REF_VAR

    - name: Publish Frontend Helm charts
      uses: stefanprodan/helm-gh-pages@master
      with:
        token: ${{ secrets.GH_TOKEN }}
        target_dir: ./air-tracker
        owner: wojcikmm
        repository: helm-repo
        branch: master
        commit_username: wojcikmm
