name: Publish Helm Release

on:
  push:
    branches: [ master ]
    paths:
      - "charts/**"
  pull_request:
    branches: [ master ]

jobs:
  build-helm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Publish Frontend Helm charts
      uses: stefanprodan/helm-gh-pages@master
      with:
        token: ${{ secrets.GH_TOKEN }}
        target_dir: ./air-tracker
        owner: wojcikmm
        repository: helm-repo
        branch: master
        commit_username: wojcikmm
