name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  docker_repo: 'wojcikmm.azurecr.io'
  image_name: 'air-tracker-app'
  image_tag: 'dev'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build ./frontend --file Dockerfile --tag $docker_repo/$image_name:$image_tag
