name: Build Frontend

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  docker_repo: 'wojcikmm'
  image_name: 'air-tracker-app'
  image_tag: 'dev'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build the Docker image
      run: |
          docker login -u wojcikmm -p ${{ secrets.DOCKERHUB_PWD }}
          docker build ./frontend --file ./frontend/Dockerfile --tag $docker_repo/$image_name:$image_tag
          docker push $docker_repo/$image_name:$image_tag
    - name: Docker Logout
      run: docker logout
   
