name: Build Frontend

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  docker_repo: 'wojcikmm.azurecr.io'
  image_name: 'air-tracker-app'
  image_tag: 'dev'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: ACR build
      id: acr
      uses: ams0/acr-task-github-action@v1
      with:
        service_principal: wojcikmm
        service_principal_password: ${{ secrets.DOCKER_PWD }}
        tenant: ${{ secrets.ACR_TENANT_ID }}
        registry: wojcikmm
        repository: $docker_repo
        image: $image_name
        #git_access_token: ${{ secrets.git_access_token }}
        folder: ./frontend
        dockerfile: ./frontend/Dockerfile
