name: Build Frontend Helm Package

on:
  push:
    branches: [ master ]
    #paths:
    #  - "charts/air-tracker-app/**"
  pull_request:
    branches: [ master ]

jobs:
  build-helm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Publish Helm charts
      uses: stefanprodan/helm-gh-pages@master
      with:
        token: ${{ secrets.helm_gh_pages_repo_token }}
        target_dir: ./air-tracker-app
        owner: wojcikmm
        repository: helm-repo
        branch: master
   
